### ISSUE TITLE
operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by wa1618i** [neurospin/pylearn-parsimony#20]
I want to apply LinearRegressionL2SmoothedL1TV into my dataset:

import parsimony.estimators as estimators
import parsimony.algorithms as algorithms
import parsimony.functions.nesterov.l1tv as l1tv
from util import Dataset
import parsimony.algorithms.primaldual as primaldual
import numpy as np
X=pd.read_csv('/home/lemma/train.csv')
y=pd.read_csv('/home/lemma/y.csv')
y=np.log(y)
l1=0.1
l2=0.9
tv=1.0
mask=np.zeros(X.shape)
mask[1:(X.shape[0] - 1), 0:(X.shape[1] - 1)] = 1
A = l1tv.linear_operator_from_mask(mask, X.shape[1], penalty_start=0)
lr = estimators.LinearRegressionL2SmoothedL1TV(l2, l1, tv, A,
                     algorithm=primaldual.ExcessiveGapMethod(),
                     algorithm_params=dict(max_iter=1000),
                     mean=False)
res = lr.fit(X, y)
y_pred=res.predict(X)
ValueError: operands could not be broadcast together with shapes (14,1) (2448108,1) (14,1)

Not sure what's going on? 
My train data shape is (188314,14) and y_train is (188314,)

**Comment by tomlof** [comment]
It seems to be your mask that is causing this problem. The mask should have the same number of elements as a row in your X matrix. This is useful if your rows are images, for instance, and you only want to compute the TV penalty within a mask, and ignore pixels outside of the mask.

**Comment by wa1618i** [comment]
@tomlof Thanks. It seems i applied the wrong estimator as mine is not an image data.
