### ISSUE TITLE
INFO_PROVIDED for the static Conesta algorithm

### ISSUE THREAD

**Issue by FH235918** [neurospin/pylearn-parsimony#6]
When tying to add a unit test for the static Conesta, I noticed that using the gap is a very good idea to test whether the algorithm converged correctly. This is especially useful when testing the logistic regression model since in this case no explicit solution is known. So, I added Info.gap to the satic_Conesta 's INFO_PROVIDED in the proximal file.

**Comment by duchesnay** [comment]
done
