### ISSUE TITLE
Error in the tutorial/example page

### ISSUE THREAD

**Issue by philouc** [neurospin/pylearn-parsimony#7]
When running the block 
k = 0.0  # l2 ridge regression coefficient
l = 0.0  # l1 lasso coefficient
g = 1.0  # tv coefficient
A, n_compacts = tv.linear_operator_from_shape(shape)  # Memory allocation for TV
olstv = estimators.LinearRegressionL1L2TV(k, l, g, A, mu=0.0001,
                                         algorithm=algorithms.explicit.FISTA(),
                                         algorithm_params=dict(max_iter=1000))

you end up with the following error in the call to LinearRegressionL1L2TV:
AttributeError: 'module' object has no attribute 'explicit'

Apparently, algorithms no longer has an 'explici't attribute

Please fix it!

**Comment by tomlof** [comment]
Great, thank you! Fixed now in commit 15134fe0ad85e20c0fdf4c7a7ae97575df9f84ad.

**Comment by philouc** [comment]
You're very welcome Tommy
